nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(default:!^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$! CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'X-Requested-With']
        expose_headers: ['Link']
        allow_credentials: true
        max_age: 3600
    paths:
        '^/api/': ~
        '^/(?:_wdt|_profiler)': ~
